-- DooriDoori MVP mock content seed data
-- Generated from dooridoori_mvp_content_items.json
-- Safe for local/dev seeding. It deletes and reinserts only rows tagged with source_refs.seed_batch = dooridoori_mvp_mock_v1.

begin;

delete from public.content_items
where source_refs->>'seed_batch' = 'dooridoori_mvp_mock_v1';

insert into public.content_items (
  title,
  type,
  category,
  subcategories,
  area,
  city,
  address,
  lat,
  lng,
  budget_level,
  vibe_tags,
  activity_tags,
  short_description,
  detail_description,
  image_url,
  source_type,
  source_refs,
  quality_score,
  korean_community_fit,
  is_active,
  is_approved,
  view_count,
  save_count,
  review_count,
  average_rating,
  start_at,
  end_at,
  created_at,
  updated_at
) values
(
  '한옥사랑 (Hanok Sarang)',
  'place',
  'food',
  ARRAY['restaurant']::text[],
  'coquitlam',
  'Coquitlam',
  '1163 Pinetree Way, Coquitlam, BC V3B 8A9',
  49.2812,
  -122.8047,
  'medium',
  ARRAY['traditional', 'family_friendly', 'cozy', 'authentic']::text[],
  ARRAY['restaurant', 'korean_community', 'korean_friendly', 'newcomer_friendly', 'student_friendly', 'family_friendly', 'curated_for_vancouver_koreans']::text[],
  'Coquitlam 한인타운에 위치한 정통 한식당. 갈비찜과 김치찌개로 유명하며, 가족 단위 손님과 향수병 달래러 오는 유학생들이 많이 찾는다. 한국에서 직수입한 식재료를 사용해 본토의 맛을 재현.',
  'Coquitlam 한인타운에 위치한 정통 한식당. 갈비찜과 김치찌개로 유명하며, 가족 단위 손님과 향수병 달래러 오는 유학생들이 많이 찾는다. 한국에서 직수입한 식재료를 사용해 본토의 맛을 재현.',
  '/mockup/images/food_001.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"food_001","name_en":"Hanok Sarang","name_kr":"한옥사랑","district":"Coquitlam","subcategory_display_kr":"식당","original_source_type":"manual","data_quality":"mock","price_tier":"$$","price_level":2,"korean_relevance_tags":["korean_community","korean_friendly","newcomer_friendly","student_friendly","family_friendly","curated_for_vancouver_koreans"],"schedule":{"type":"recurring","openingHours":"Mon-Sun 11:00-22:00","startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":3,"taste":4.5,"service":4,"value_for_money":4},"metadata":{"cuisineType":"Korean","soloFriendly":false,"groupFriendly":true},"popularity_score":0.83,"freshness_score":0.65}$json$::jsonb,
  0.766,
  1,
  true,
  true,
  100,
  20,
  2,
  3.9,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '슬로우 모닝 (Slow Morning)',
  'place',
  'food',
  ARRAY['cafe']::text[],
  'vancouver',
  'Vancouver',
  '2588 Main St, Vancouver, BC V5T 3E2',
  49.2647,
  -123.1018,
  'low',
  ARRAY['minimalist', 'study_friendly', 'third_wave', 'trendy']::text[],
  ARRAY['cafe', 'curated_for_vancouver_koreans']::text[],
  'Mount Pleasant에 위치한 스페셜티 커피 로스터리. 직접 로스팅한 싱글 오리진 원두와 핸드드립이 시그니처. 노트북 작업하기 좋은 차분한 분위기로 프리랜서와 작가들이 단골.',
  'Mount Pleasant에 위치한 스페셜티 커피 로스터리. 직접 로스팅한 싱글 오리진 원두와 핸드드립이 시그니처. 노트북 작업하기 좋은 차분한 분위기로 프리랜서와 작가들이 단골.',
  '/mockup/images/food_002.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"food_002","name_en":"Slow Morning","name_kr":"슬로우 모닝","district":"Mount Pleasant","subcategory_display_kr":"카페","original_source_type":"manual","data_quality":"mock","price_tier":"$","price_level":1,"korean_relevance_tags":["curated_for_vancouver_koreans"],"schedule":{"type":"recurring","openingHours":"Mon-Sun 8:00-19:00","startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":1.5,"taste":4.5,"service":3.5,"value_for_money":4.5},"metadata":{"cuisineType":null,"soloFriendly":true,"groupFriendly":false},"popularity_score":0.73,"freshness_score":0.65}$json$::jsonb,
  0.699,
  0.6,
  true,
  true,
  88,
  18,
  2,
  3.5,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '메종 루미에르 (Maison Lumière)',
  'place',
  'food',
  ARRAY['restaurant']::text[],
  'vancouver',
  'Vancouver',
  '1180 Hamilton St, Vancouver, BC V6B 2S2',
  49.2756,
  -123.1219,
  'high',
  ARRAY['upscale', 'date_night', 'instagrammable', 'modern']::text[],
  ARRAY['restaurant', 'curated_for_vancouver_koreans']::text[],
  'Yaletown에 자리한 모던 프렌치 비스트로. 로컬 재료로 만든 시즌 메뉴와 와인 페어링이 강점. 데이트나 기념일에 많이 찾으며, 셰프의 오픈 키친에서 진행되는 코스 디너가 시그니처.',
  'Yaletown에 자리한 모던 프렌치 비스트로. 로컬 재료로 만든 시즌 메뉴와 와인 페어링이 강점. 데이트나 기념일에 많이 찾으며, 셰프의 오픈 키친에서 진행되는 코스 디너가 시그니처.',
  '/mockup/images/food_003.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"food_003","name_en":"Maison Lumière","name_kr":"메종 루미에르","district":"Yaletown","subcategory_display_kr":"식당","original_source_type":"manual","data_quality":"mock","price_tier":"$$$$","price_level":4,"korean_relevance_tags":["curated_for_vancouver_koreans"],"schedule":{"type":"recurring","openingHours":"Tue-Sun 17:30-22:30, Closed Mon","startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":4,"taste":4.5,"service":5,"value_for_money":3},"metadata":{"cuisineType":"Western","soloFriendly":false,"groupFriendly":true},"popularity_score":0.88,"freshness_score":0.65}$json$::jsonb,
  0.806,
  0.6,
  true,
  true,
  106,
  21,
  3,
  4.1,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '사쿠라 이자카야 (Sakura Izakaya)',
  'place',
  'food',
  ARRAY['restaurant']::text[],
  'vancouver',
  'Vancouver',
  '1789 Robson St, Vancouver, BC V6G 1E5',
  49.2842,
  -123.1267,
  'high',
  ARRAY['lively', 'after_work', 'group_friendly', 'casual']::text[],
  ARRAY['restaurant', 'curated_for_vancouver_koreans']::text[],
  'Robson Street의 활기찬 일본식 이자카야. 직장인 퇴근 모임과 친구 모임으로 시끌벅적한 분위기. 야키토리와 사케 페어링 메뉴가 인기. 합석 테이블에서 처음 보는 사람과 친해지는 일도 흔하다.',
  'Robson Street의 활기찬 일본식 이자카야. 직장인 퇴근 모임과 친구 모임으로 시끌벅적한 분위기. 야키토리와 사케 페어링 메뉴가 인기. 합석 테이블에서 처음 보는 사람과 친해지는 일도 흔하다.',
  '/mockup/images/food_004.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"food_004","name_en":"Sakura Izakaya","name_kr":"사쿠라 이자카야","district":"West End","subcategory_display_kr":"식당","original_source_type":"manual","data_quality":"mock","price_tier":"$$$","price_level":3,"korean_relevance_tags":["curated_for_vancouver_koreans"],"schedule":{"type":"recurring","openingHours":"Mon-Sun 17:00-24:00","startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":4.5,"taste":4,"service":3.5,"value_for_money":3.5},"metadata":{"cuisineType":"Japanese","soloFriendly":false,"groupFriendly":true},"popularity_score":0.83,"freshness_score":0.65}$json$::jsonb,
  0.766,
  0.6,
  true,
  true,
  100,
  20,
  2,
  3.9,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '골든 워크 (Golden Wok)',
  'place',
  'food',
  ARRAY['restaurant']::text[],
  'richmond',
  'Richmond',
  '8060 Westminster Hwy, Richmond, BC V6X 1A7',
  49.1666,
  -123.1336,
  'medium',
  ARRAY['authentic', 'family_friendly', 'traditional', 'lively']::text[],
  ARRAY['restaurant', 'family_friendly', 'curated_for_vancouver_koreans']::text[],
  'Richmond의 정통 광동식 딤섬 레스토랑. 주말 점심시간에는 30분 이상 대기가 기본. 카트 서비스로 즉석에서 골라 먹는 전통 방식 유지. 가족 단위와 중국계 커뮤니티가 주 고객.',
  'Richmond의 정통 광동식 딤섬 레스토랑. 주말 점심시간에는 30분 이상 대기가 기본. 카트 서비스로 즉석에서 골라 먹는 전통 방식 유지. 가족 단위와 중국계 커뮤니티가 주 고객.',
  '/mockup/images/food_005.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"food_005","name_en":"Golden Wok","name_kr":"골든 워크","district":"Richmond","subcategory_display_kr":"식당","original_source_type":"manual","data_quality":"mock","price_tier":"$$","price_level":2,"korean_relevance_tags":["family_friendly","curated_for_vancouver_koreans"],"schedule":{"type":"recurring","openingHours":"Mon-Sun 9:30-15:00, 17:00-22:00","startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":3.5,"taste":4.5,"service":3,"value_for_money":4.5},"metadata":{"cuisineType":"Chinese","soloFriendly":false,"groupFriendly":true},"popularity_score":0.83,"freshness_score":0.65}$json$::jsonb,
  0.766,
  0.6,
  true,
  true,
  100,
  20,
  2,
  3.9,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '에그 앤 스톤 (Egg & Stone)',
  'place',
  'food',
  ARRAY['restaurant']::text[],
  'vancouver',
  'Vancouver',
  '2095 W 4th Ave, Vancouver, BC V6J 1N3',
  49.2706,
  -123.1539,
  'medium',
  ARRAY['instagrammable', 'brunch_spot', 'trendy', 'bright']::text[],
  ARRAY['restaurant', 'curated_for_vancouver_koreans']::text[],
  'Kitsilano의 인기 브런치 스팟. 주말이면 1시간 대기는 기본인 동네 명소. 트러플 에그 베네딕트와 리코타 팬케이크가 시그니처. 인스타에 자주 올라오는 비주얼과 자연광 가득한 인테리어.',
  'Kitsilano의 인기 브런치 스팟. 주말이면 1시간 대기는 기본인 동네 명소. 트러플 에그 베네딕트와 리코타 팬케이크가 시그니처. 인스타에 자주 올라오는 비주얼과 자연광 가득한 인테리어.',
  '/mockup/images/food_006.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"food_006","name_en":"Egg & Stone","name_kr":"에그 앤 스톤","district":"Kitsilano","subcategory_display_kr":"식당","original_source_type":"manual","data_quality":"mock","price_tier":"$$","price_level":2,"korean_relevance_tags":["curated_for_vancouver_koreans"],"schedule":{"type":"recurring","openingHours":"Mon-Sun 8:00-15:00","startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":3,"taste":4,"service":3.5,"value_for_money":3.5},"metadata":{"cuisineType":"Brunch","soloFriendly":true,"groupFriendly":true},"popularity_score":0.78,"freshness_score":0.65}$json$::jsonb,
  0.714,
  0.6,
  true,
  true,
  94,
  19,
  2,
  3.5,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '빈티지 하우스 (Vintage House)',
  'place',
  'food',
  ARRAY['cafe']::text[],
  'vancouver',
  'Vancouver',
  '210 Carrall St, Vancouver, BC V6B 2J1',
  49.2839,
  -123.1067,
  'medium',
  ARRAY['vintage', 'hidden_gem', 'cozy', 'instagrammable']::text[],
  ARRAY['cafe', 'curated_for_vancouver_koreans']::text[],
  'Gastown 좁은 골목에 숨어 있는 빈티지 컨셉 카페. 1970년대 LP와 골동품 가구로 채워진 공간. 시그니처 메뉴는 흑임자 라떼와 호두 파이. 천천히 책 읽기 좋은 곳.',
  'Gastown 좁은 골목에 숨어 있는 빈티지 컨셉 카페. 1970년대 LP와 골동품 가구로 채워진 공간. 시그니처 메뉴는 흑임자 라떼와 호두 파이. 천천히 책 읽기 좋은 곳.',
  '/mockup/images/food_007.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"food_007","name_en":"Vintage House","name_kr":"빈티지 하우스","district":"Gastown","subcategory_display_kr":"카페","original_source_type":"manual","data_quality":"mock","price_tier":"$$","price_level":2,"korean_relevance_tags":["curated_for_vancouver_koreans"],"schedule":{"type":"recurring","openingHours":"Wed-Sun 10:00-19:00, Closed Mon-Tue","startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":2,"taste":3.5,"service":4,"value_for_money":3.5},"metadata":{"cuisineType":null,"soloFriendly":true,"groupFriendly":false},"popularity_score":0.68,"freshness_score":0.65}$json$::jsonb,
  0.659,
  0.6,
  true,
  true,
  82,
  16,
  2,
  3.2,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '데일리 그라인드 (Daily Grind)',
  'place',
  'food',
  ARRAY['cafe']::text[],
  'vancouver',
  'Vancouver',
  '888 Burrard St, Vancouver, BC V6Z 1X9',
  49.2848,
  -123.1145,
  'low',
  ARRAY['casual', 'grab_and_go', 'modern']::text[],
  ARRAY['cafe', 'curated_for_vancouver_koreans']::text[],
  'Downtown 비즈니스 지구의 캐주얼 체인 카페. 출근길 직장인들의 빠른 커피 픽업 장소. 가격 대비 양 많은 시그니처 라떼와 베이글 콤보가 강점. 자리는 좁지만 회전율 빠름.',
  'Downtown 비즈니스 지구의 캐주얼 체인 카페. 출근길 직장인들의 빠른 커피 픽업 장소. 가격 대비 양 많은 시그니처 라떼와 베이글 콤보가 강점. 자리는 좁지만 회전율 빠름.',
  '/mockup/images/food_008.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"food_008","name_en":"Daily Grind","name_kr":"데일리 그라인드","district":"Downtown","subcategory_display_kr":"카페","original_source_type":"manual","data_quality":"mock","price_tier":"$","price_level":1,"korean_relevance_tags":["curated_for_vancouver_koreans"],"schedule":{"type":"recurring","openingHours":"Mon-Fri 6:30-18:00, Sat-Sun 8:00-17:00","startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":2.5,"taste":2.5,"service":3,"value_for_money":4},"metadata":{"cuisineType":null,"soloFriendly":true,"groupFriendly":false},"popularity_score":0.63,"freshness_score":0.65}$json$::jsonb,
  0.619,
  0.6,
  true,
  true,
  76,
  15,
  2,
  3.0,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '벨벳 라운지 (The Velvet Lounge)',
  'place',
  'food',
  ARRAY['bar']::text[],
  'vancouver',
  'Vancouver',
  '1132 Hamilton St, Vancouver, BC V6B 2S2',
  49.2734,
  -123.1208,
  'high',
  ARRAY['upscale', 'date_night', 'late_night', 'intimate']::text[],
  ARRAY['bar', 'curated_for_vancouver_koreans']::text[],
  'Yaletown 지하에 위치한 시그니처 칵테일 바. 헤드 바텐더가 직접 만드는 시즌 칵테일과 어둑한 조명, 라이브 재즈가 주말마다 진행. 데이트 코스나 친구 모임의 마무리 장소로 인기.',
  'Yaletown 지하에 위치한 시그니처 칵테일 바. 헤드 바텐더가 직접 만드는 시즌 칵테일과 어둑한 조명, 라이브 재즈가 주말마다 진행. 데이트 코스나 친구 모임의 마무리 장소로 인기.',
  '/mockup/images/food_009.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"food_009","name_en":"The Velvet Lounge","name_kr":"벨벳 라운지","district":"Yaletown","subcategory_display_kr":"바","original_source_type":"manual","data_quality":"mock","price_tier":"$$$","price_level":3,"korean_relevance_tags":["curated_for_vancouver_koreans"],"schedule":{"type":"recurring","openingHours":"Tue-Sat 18:00-02:00, Closed Sun-Mon","startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":4,"taste":4.5,"service":4.5,"value_for_money":3},"metadata":{"cuisineType":null,"soloFriendly":false,"groupFriendly":true},"popularity_score":0.85,"freshness_score":0.65}$json$::jsonb,
  0.785,
  0.6,
  true,
  true,
  102,
  20,
  2,
  4.0,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '선셋 브루잉 (Sunset Brewing Co.)',
  'place',
  'food',
  ARRAY['bar']::text[],
  'vancouver',
  'Vancouver',
  '2125 Main St, Vancouver, BC V5T 3C5',
  49.2658,
  -123.1011,
  'medium',
  ARRAY['lively', 'casual', 'group_friendly', 'outdoor']::text[],
  ARRAY['bar', 'curated_for_vancouver_koreans']::text[],
  'Mount Pleasant의 크래프트 비어 브루어리 탭룸. 매주 새로운 시즌 IPA 출시. 야외 패티오에서 강아지 동반 가능하며, 트럭 푸드 트럭이 주말마다 다른 메뉴로 등장. 캐주얼하고 시끌벅적한 분위기.',
  'Mount Pleasant의 크래프트 비어 브루어리 탭룸. 매주 새로운 시즌 IPA 출시. 야외 패티오에서 강아지 동반 가능하며, 트럭 푸드 트럭이 주말마다 다른 메뉴로 등장. 캐주얼하고 시끌벅적한 분위기.',
  '/mockup/images/food_010.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"food_010","name_en":"Sunset Brewing Co.","name_kr":"선셋 브루잉","district":"Mount Pleasant","subcategory_display_kr":"바","original_source_type":"manual","data_quality":"mock","price_tier":"$$","price_level":2,"korean_relevance_tags":["curated_for_vancouver_koreans"],"schedule":{"type":"recurring","openingHours":"Mon-Sun 15:00-23:00","startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":4.5,"taste":4,"service":3.5,"value_for_money":4},"metadata":{"cuisineType":null,"soloFriendly":false,"groupFriendly":true},"popularity_score":0.85,"freshness_score":0.65}$json$::jsonb,
  0.785,
  0.6,
  true,
  true,
  102,
  20,
  2,
  4.0,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '밴쿠버 한식 미식 모임 (Vancouver Korean Foodie Meetup)',
  'event',
  'events',
  ARRAY['social']::text[],
  'coquitlam',
  'Coquitlam',
  'Coquitlam 한식당 (매월 변경)',
  49.2812,
  -122.8047,
  'medium',
  ARRAY['casual', 'korean_community', 'expat_friendly', 'group_friendly']::text[],
  ARRAY['social', 'korean_community', 'korean_friendly', 'expat_friendly', 'curated_for_vancouver_koreans']::text[],
  'Vancouver에서 한식 좋아하는 사람들이 매달 모이는 친목 모임. 매번 다른 한식당에서 함께 식사하며 음식 이야기와 일상 공유. 현지인·한인·교포 누구나 환영하는 캐주얼한 분위기.',
  'Vancouver에서 한식 좋아하는 사람들이 매달 모이는 친목 모임. 매번 다른 한식당에서 함께 식사하며 음식 이야기와 일상 공유. 현지인·한인·교포 누구나 환영하는 캐주얼한 분위기.',
  '/mockup/images/event_001.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"event_001","name_en":"Vancouver Korean Foodie Meetup","name_kr":"밴쿠버 한식 미식 모임","district":"Coquitlam","subcategory_display_kr":"일반소셜","original_source_type":"manual","data_quality":"mock","price_tier":"$$","price_level":2,"korean_relevance_tags":["korean_community","korean_friendly","expat_friendly","curated_for_vancouver_koreans"],"schedule":{"type":"one_time","openingHours":null,"startDateTime":"2026-05-24T18:30","endDateTime":"2026-05-24T21:00"},"dimension_scores":{"atmosphere":4,"size":2,"learning_value":2},"metadata":{"eventSubtype":"social","hostName":"Vancouver Korean Foodie Group","attendanceEstimate":25},"popularity_score":0.47,"freshness_score":0.81}$json$::jsonb,
  0.57,
  0.9,
  true,
  true,
  56,
  11,
  1,
  2.7,
  '2026-05-24T18:30:00-07:00',
  '2026-05-24T21:00:00-07:00',
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '아이언웍스 언어 교환 나잇 (Language Exchange Night at Ironworks)',
  'event',
  'events',
  ARRAY['social']::text[],
  'vancouver',
  'Vancouver',
  '235 Alexander St, Vancouver, BC V6A 1B5',
  49.2842,
  -123.1003,
  'low',
  ARRAY['casual', 'expat_friendly', 'after_work', 'alcohol_served']::text[],
  ARRAY['social', 'korean_community', 'korean_friendly', 'expat_friendly', 'language_exchange', 'curated_for_vancouver_koreans']::text[],
  'Gastown 펍에서 매주 목요일 진행되는 언어 교환 모임. 영어·한국어·일본어·스페인어 테이블 운영. 음료 한잔 하면서 자연스럽게 대화하는 형식. 신청 없이 그냥 와도 OK.',
  'Gastown 펍에서 매주 목요일 진행되는 언어 교환 모임. 영어·한국어·일본어·스페인어 테이블 운영. 음료 한잔 하면서 자연스럽게 대화하는 형식. 신청 없이 그냥 와도 OK.',
  '/mockup/images/event_002.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"event_002","name_en":"Language Exchange Night at Ironworks","name_kr":"아이언웍스 언어 교환 나잇","district":"Gastown","subcategory_display_kr":"일반소셜","original_source_type":"manual","data_quality":"mock","price_tier":"$","price_level":1,"korean_relevance_tags":["korean_community","korean_friendly","expat_friendly","language_exchange","curated_for_vancouver_koreans"],"schedule":{"type":"one_time","openingHours":null,"startDateTime":"2026-05-21T19:00","endDateTime":"2026-05-21T22:00"},"dimension_scores":{"atmosphere":3.5,"size":2.5,"learning_value":3},"metadata":{"eventSubtype":"social","hostName":"Vancouver Language Exchange","attendanceEstimate":60},"popularity_score":0.55,"freshness_score":0.85}$json$::jsonb,
  0.635,
  0.95,
  true,
  true,
  66,
  13,
  1,
  3.0,
  '2026-05-21T19:00:00-07:00',
  '2026-05-21T22:00:00-07:00',
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '스패니쉬 뱅크 선셋 피크닉 (Sunset Picnic at Spanish Banks)',
  'event',
  'events',
  ARRAY['social']::text[],
  'vancouver',
  'Vancouver',
  'Spanish Banks Beach, Vancouver, BC',
  49.2766,
  -123.2031,
  'low',
  ARRAY['casual', 'outdoor', 'newcomer_friendly', 'free_entry']::text[],
  ARRAY['social', 'newcomer_friendly', 'curated_for_vancouver_koreans']::text[],
  'Spanish Banks Beach에서 매달 보름달 시기에 열리는 캐주얼 피크닉. 각자 음식 가져와서 노을 보며 이야기 나누는 자유로운 분위기. 처음 온 사람도 환영하는 newcomer-friendly 모임.',
  'Spanish Banks Beach에서 매달 보름달 시기에 열리는 캐주얼 피크닉. 각자 음식 가져와서 노을 보며 이야기 나누는 자유로운 분위기. 처음 온 사람도 환영하는 newcomer-friendly 모임.',
  '/mockup/images/event_003.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"event_003","name_en":"Sunset Picnic at Spanish Banks","name_kr":"스패니쉬 뱅크 선셋 피크닉","district":"West Point Grey","subcategory_display_kr":"일반소셜","original_source_type":"manual","data_quality":"mock","price_tier":"free","price_level":0,"korean_relevance_tags":["newcomer_friendly","curated_for_vancouver_koreans"],"schedule":{"type":"one_time","openingHours":null,"startDateTime":"2026-06-08T19:00","endDateTime":"2026-06-08T22:00"},"dimension_scores":{"atmosphere":3,"size":2,"learning_value":1},"metadata":{"eventSubtype":"social","hostName":"Vancouver Newcomers Circle","attendanceEstimate":30},"popularity_score":0.4,"freshness_score":0.61}$json$::jsonb,
  0.442,
  0.67,
  true,
  true,
  48,
  10,
  1,
  2.0,
  '2026-06-08T19:00:00-07:00',
  '2026-06-08T22:00:00-07:00',
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '밴쿠버 테크 서밋 2026 (Vancouver Tech Summit 2026)',
  'event',
  'events',
  ARRAY['career']::text[],
  'vancouver',
  'Vancouver',
  '1055 Canada Pl, Vancouver, BC V6C 0C3',
  49.2891,
  -123.1167,
  'high',
  ARRAY['formal', 'networking_heavy', 'learning_heavy', 'ticket_required']::text[],
  ARRAY['career', 'career_useful', 'curated_for_vancouver_koreans']::text[],
  'Vancouver Convention Centre에서 열리는 BC 최대 규모 테크 컨퍼런스. AI·핀테크·SaaS 트렌드 발표와 1,500+ 참가자 네트워킹 세션. 키노트는 글로벌 테크 기업 임원진.',
  'Vancouver Convention Centre에서 열리는 BC 최대 규모 테크 컨퍼런스. AI·핀테크·SaaS 트렌드 발표와 1,500+ 참가자 네트워킹 세션. 키노트는 글로벌 테크 기업 임원진.',
  '/mockup/images/event_004.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"event_004","name_en":"Vancouver Tech Summit 2026","name_kr":"밴쿠버 테크 서밋 2026","district":"Downtown","subcategory_display_kr":"커리어","original_source_type":"manual","data_quality":"mock","price_tier":"$$$$","price_level":4,"korean_relevance_tags":["career_useful","curated_for_vancouver_koreans"],"schedule":{"type":"one_time","openingHours":null,"startDateTime":"2026-06-15T09:00","endDateTime":"2026-06-16T18:00"},"dimension_scores":{"atmosphere":2.5,"size":5,"learning_value":4.5},"metadata":{"eventSubtype":"career","hostName":"BC Tech Association","attendanceEstimate":1500},"popularity_score":0.83,"freshness_score":0.57}$json$::jsonb,
  0.763,
  0.65,
  true,
  true,
  100,
  20,
  2,
  4.0,
  '2026-06-15T09:00:00-07:00',
  '2026-06-16T18:00:00-07:00',
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '이민자 대상 데이터 커리어 워크숍 (Data Career Workshop for Newcomers)',
  'event',
  'events',
  ARRAY['career']::text[],
  'vancouver',
  'Vancouver',
  '350 W Georgia St, Vancouver, BC V6B 6B1',
  49.279,
  -123.1158,
  'low',
  ARRAY['learning_heavy', 'newcomer_friendly', 'free_entry', 'career_focused']::text[],
  ARRAY['career', 'korean_community', 'korean_friendly', 'newcomer_friendly', 'career_useful', 'student_friendly', 'curated_for_vancouver_koreans']::text[],
  'Vancouver Public Library에서 열리는 무료 워크숍. 캐나다 데이터 직군 취업 가이드, 이력서 리뷰, 1:1 멘토링 세션 포함. 신규 이민자와 유학생 대상으로 한국·중국·인도 출신 멘토 다수 참여.',
  'Vancouver Public Library에서 열리는 무료 워크숍. 캐나다 데이터 직군 취업 가이드, 이력서 리뷰, 1:1 멘토링 세션 포함. 신규 이민자와 유학생 대상으로 한국·중국·인도 출신 멘토 다수 참여.',
  '/mockup/images/event_005.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"event_005","name_en":"Data Career Workshop for Newcomers","name_kr":"이민자 대상 데이터 커리어 워크숍","district":"Downtown","subcategory_display_kr":"커리어","original_source_type":"manual","data_quality":"mock","price_tier":"free","price_level":0,"korean_relevance_tags":["korean_community","korean_friendly","newcomer_friendly","career_useful","student_friendly","curated_for_vancouver_koreans"],"schedule":{"type":"one_time","openingHours":null,"startDateTime":"2026-05-30T13:00","endDateTime":"2026-05-30T17:00"},"dimension_scores":{"atmosphere":2,"size":3,"learning_value":5},"metadata":{"eventSubtype":"career","hostName":"Vancouver Data Professionals Network","attendanceEstimate":80},"popularity_score":0.6,"freshness_score":0.73}$json$::jsonb,
  0.659,
  1,
  true,
  true,
  72,
  14,
  1,
  3.3,
  '2026-05-30T13:00:00-07:00',
  '2026-05-30T17:00:00-07:00',
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '스타트업 파운더 애프터워크 드링크 (Startup Founders After-Work Drinks)',
  'event',
  'events',
  ARRAY['career']::text[],
  'vancouver',
  'Vancouver',
  '1112 Hamilton St (Rooftop), Vancouver, BC',
  49.2756,
  -123.1219,
  'medium',
  ARRAY['networking_heavy', 'after_work', 'casual', 'alcohol_served']::text[],
  ARRAY['career', 'career_useful', 'curated_for_vancouver_koreans']::text[],
  'Yaletown 루프탑 바에서 매달 진행되는 스타트업 창업자·투자자 네트워킹 모임. 격식 없는 분위기에서 비즈니스 카드 교환과 자연스러운 대화. 초대 기반이지만 LinkedIn 신청 가능.',
  'Yaletown 루프탑 바에서 매달 진행되는 스타트업 창업자·투자자 네트워킹 모임. 격식 없는 분위기에서 비즈니스 카드 교환과 자연스러운 대화. 초대 기반이지만 LinkedIn 신청 가능.',
  '/mockup/images/event_006.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"event_006","name_en":"Startup Founders After-Work Drinks","name_kr":"스타트업 파운더 애프터워크 드링크","district":"Yaletown","subcategory_display_kr":"커리어","original_source_type":"manual","data_quality":"mock","price_tier":"$$","price_level":2,"korean_relevance_tags":["career_useful","curated_for_vancouver_koreans"],"schedule":{"type":"one_time","openingHours":null,"startDateTime":"2026-05-29T18:30","endDateTime":"2026-05-29T21:30"},"dimension_scores":{"atmosphere":3.5,"size":2.5,"learning_value":3},"metadata":{"eventSubtype":"career","hostName":"BC Founders Circle","attendanceEstimate":50},"popularity_score":0.54,"freshness_score":0.74}$json$::jsonb,
  0.61,
  0.65,
  true,
  true,
  65,
  13,
  1,
  3.0,
  '2026-05-29T18:30:00-07:00',
  '2026-05-29T21:30:00-07:00',
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  'BC 테크 잡 페어 스프링 2026 (BC Tech Job Fair Spring 2026)',
  'event',
  'events',
  ARRAY['career']::text[],
  'burnaby',
  'Burnaby',
  '8888 University Dr, Burnaby, BC V5A 1S6',
  49.2781,
  -122.9199,
  'low',
  ARRAY['formal', 'career_focused', 'newcomer_friendly', 'free_entry']::text[],
  ARRAY['career', 'newcomer_friendly', 'career_useful', 'student_friendly', 'curated_for_vancouver_koreans']::text[],
  'SFU Burnaby 캠퍼스에서 진행되는 봄철 잡 페어. 60+ BC 테크 기업 부스 운영, 현장 면접 가능. 신입·주니어 포지션 위주이며, 워크 비자·LMIA 지원 가능 기업이 별도 표시됨.',
  'SFU Burnaby 캠퍼스에서 진행되는 봄철 잡 페어. 60+ BC 테크 기업 부스 운영, 현장 면접 가능. 신입·주니어 포지션 위주이며, 워크 비자·LMIA 지원 가능 기업이 별도 표시됨.',
  '/mockup/images/event_007.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"event_007","name_en":"BC Tech Job Fair Spring 2026","name_kr":"BC 테크 잡 페어 스프링 2026","district":"Burnaby","subcategory_display_kr":"커리어","original_source_type":"manual","data_quality":"mock","price_tier":"free","price_level":0,"korean_relevance_tags":["newcomer_friendly","career_useful","student_friendly","curated_for_vancouver_koreans"],"schedule":{"type":"one_time","openingHours":null,"startDateTime":"2026-05-17T10:00","endDateTime":"2026-05-17T16:00"},"dimension_scores":{"atmosphere":2,"size":4.5,"learning_value":4},"metadata":{"eventSubtype":"career","hostName":"BC Tech Association","attendanceEstimate":800},"popularity_score":0.74,"freshness_score":1.0}$json$::jsonb,
  0.772,
  0.77,
  true,
  true,
  89,
  18,
  2,
  3.5,
  '2026-05-17T10:00:00-07:00',
  '2026-05-17T16:00:00-07:00',
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  'DOXA 다큐멘터리 영화제 (DOXA Documentary Film Festival)',
  'event',
  'events',
  ARRAY['arts_culture']::text[],
  'vancouver',
  'Vancouver',
  '149 W Hastings St, Vancouver, BC V6B 1H4',
  49.2823,
  -123.1085,
  'medium',
  ARRAY['formal', 'ticket_required', 'learning_heavy', 'indoor']::text[],
  ARRAY['arts_culture', 'student_friendly', 'curated_for_vancouver_koreans']::text[],
  'Vancouver의 대표 다큐멘터리 영화제. 매년 5월 SFU Goldcorp Centre, Vancity Theatre 등 여러 극장에서 진행. 글로벌 다큐 80+편 상영, 감독과의 Q&A 세션 다수.',
  'Vancouver의 대표 다큐멘터리 영화제. 매년 5월 SFU Goldcorp Centre, Vancity Theatre 등 여러 극장에서 진행. 글로벌 다큐 80+편 상영, 감독과의 Q&A 세션 다수.',
  '/mockup/images/event_008.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"event_008","name_en":"DOXA Documentary Film Festival","name_kr":"DOXA 다큐멘터리 영화제","district":"Downtown","subcategory_display_kr":"아트&컬쳐","original_source_type":"manual","data_quality":"mock","price_tier":"$$","price_level":2,"korean_relevance_tags":["student_friendly","curated_for_vancouver_koreans"],"schedule":{"type":"one_time","openingHours":null,"startDateTime":"2026-05-08T18:00","endDateTime":"2026-05-18T22:00"},"dimension_scores":{"atmosphere":2.5,"size":4,"learning_value":4},"metadata":{"eventSubtype":"arts_culture","hostName":"DOXA Documentary Film Festival Society","attendanceEstimate":5000},"popularity_score":0.83,"freshness_score":0.1}$json$::jsonb,
  0.619,
  0.65,
  true,
  true,
  100,
  20,
  2,
  3.5,
  '2026-05-08T18:00:00-07:00',
  '2026-05-18T22:00:00-07:00',
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '신진 작가 갤러리 오프닝 (Emerging Artists Gallery Opening)',
  'event',
  'events',
  ARRAY['arts_culture']::text[],
  'vancouver',
  'Vancouver',
  '1551 Johnston St, Vancouver, BC V6H 3R9',
  49.2715,
  -123.1349,
  'low',
  ARRAY['formal', 'free_entry', 'alcohol_served', 'indoor']::text[],
  ARRAY['arts_culture', 'student_friendly', 'curated_for_vancouver_koreans']::text[],
  'Granville Island의 작은 갤러리에서 열리는 신진 캐나다 작가 단체전 오프닝 리셉션. 작가 본인이 직접 작품 설명, 와인 서비스 제공. 미술 컬렉터와 학생 모두 환영하는 따뜻한 분위기.',
  'Granville Island의 작은 갤러리에서 열리는 신진 캐나다 작가 단체전 오프닝 리셉션. 작가 본인이 직접 작품 설명, 와인 서비스 제공. 미술 컬렉터와 학생 모두 환영하는 따뜻한 분위기.',
  '/mockup/images/event_009.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"event_009","name_en":"Emerging Artists Gallery Opening","name_kr":"신진 작가 갤러리 오프닝","district":"Granville Island","subcategory_display_kr":"아트&컬쳐","original_source_type":"manual","data_quality":"mock","price_tier":"free","price_level":0,"korean_relevance_tags":["student_friendly","curated_for_vancouver_koreans"],"schedule":{"type":"one_time","openingHours":null,"startDateTime":"2026-05-23T18:00","endDateTime":"2026-05-23T21:00"},"dimension_scores":{"atmosphere":2,"size":1.5,"learning_value":3},"metadata":{"eventSubtype":"arts_culture","hostName":"Granville Island Art Collective","attendanceEstimate":60},"popularity_score":0.46,"freshness_score":0.82}$json$::jsonb,
  0.519,
  0.65,
  true,
  true,
  55,
  11,
  1,
  2.2,
  '2026-05-23T18:00:00-07:00',
  '2026-05-23T21:00:00-07:00',
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '한국 인디 밴드 쇼케이스 (Korean Indie Band Showcase)',
  'event',
  'events',
  ARRAY['arts_culture']::text[],
  'vancouver',
  'Vancouver',
  '147 E Pender St, Vancouver, BC V6A 1T5',
  49.281,
  -123.1015,
  'medium',
  ARRAY['lively', 'korean_community', 'ticket_required', 'alcohol_served']::text[],
  ARRAY['arts_culture', 'korean_community', 'korean_friendly', 'curated_for_vancouver_koreans']::text[],
  'Fortune Sound Club에서 진행되는 한국 인디 밴드 4팀의 캐나다 투어 쇼케이스. 록·신스팝·인디 포크 장르 다양. 한국 음악 팬과 현지 인디 씬 마니아가 함께 모이는 자리.',
  'Fortune Sound Club에서 진행되는 한국 인디 밴드 4팀의 캐나다 투어 쇼케이스. 록·신스팝·인디 포크 장르 다양. 한국 음악 팬과 현지 인디 씬 마니아가 함께 모이는 자리.',
  '/mockup/images/event_010.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"event_010","name_en":"Korean Indie Band Showcase","name_kr":"한국 인디 밴드 쇼케이스","district":"Chinatown","subcategory_display_kr":"아트&컬쳐","original_source_type":"manual","data_quality":"mock","price_tier":"$$","price_level":2,"korean_relevance_tags":["korean_community","korean_friendly","curated_for_vancouver_koreans"],"schedule":{"type":"one_time","openingHours":null,"startDateTime":"2026-06-21T20:00","endDateTime":"2026-06-21T23:30"},"dimension_scores":{"atmosphere":4.5,"size":2.5,"learning_value":1.5},"metadata":{"eventSubtype":"arts_culture","hostName":"Fortune Sound Club","attendanceEstimate":200},"popularity_score":0.59,"freshness_score":0.55}$json$::jsonb,
  0.57,
  0.9,
  true,
  true,
  71,
  14,
  1,
  2.8,
  '2026-06-21T20:00:00-07:00',
  '2026-06-21T23:30:00-07:00',
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '하이브 클라이밍 (Hive Climbing)',
  'place',
  'lifestyle',
  ARRAY['sport_venue']::text[],
  'north_vancouver',
  'North Vancouver',
  '127 E 2nd St, North Vancouver, BC V7L 1C1',
  49.3181,
  -123.0728,
  'medium',
  ARRAY['active', 'indoor', 'beginner_friendly', 'group_required']::text[],
  ARRAY['sport_venue', 'curated_for_vancouver_koreans']::text[],
  'North Vancouver의 대형 볼더링·로프 클라이밍 짐. 초보자 대상 입문 클래스부터 상급자 코스까지 운영. 매주 새로운 루트 셋팅으로 단골들의 도전 욕구 자극. 평일 저녁과 주말은 만석.',
  'North Vancouver의 대형 볼더링·로프 클라이밍 짐. 초보자 대상 입문 클래스부터 상급자 코스까지 운영. 매주 새로운 루트 셋팅으로 단골들의 도전 욕구 자극. 평일 저녁과 주말은 만석.',
  '/mockup/images/lifestyle_001.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"lifestyle_001","name_en":"Hive Climbing","name_kr":"하이브 클라이밍","district":"North Vancouver","subcategory_display_kr":"스포츠 장소","original_source_type":"manual","data_quality":"mock","price_tier":"$$","price_level":2,"korean_relevance_tags":["curated_for_vancouver_koreans"],"schedule":{"type":"recurring","openingHours":"Mon-Fri 6:00-23:00, Sat-Sun 8:00-22:00","startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":4,"engagement":5,"production":4,"energy":5},"metadata":{"lifestyleSubtype":"sport_venue","isRecurring":true,"requiresMembership":false},"popularity_score":0.9,"freshness_score":0.65}$json$::jsonb,
  0.85,
  0.6,
  true,
  true,
  108,
  22,
  3,
  4.5,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '키츠 풀 (Kits Pool)',
  'place',
  'lifestyle',
  ARRAY['sport_venue']::text[],
  'vancouver',
  'Vancouver',
  '2305 Cornwall Ave, Vancouver, BC V6K 1B5',
  49.2729,
  -123.1606,
  'low',
  ARRAY['outdoor', 'seasonal', 'beginner_friendly', 'family_event']::text[],
  ARRAY['sport_venue', 'family_friendly', 'curated_for_vancouver_koreans']::text[],
  'Kitsilano Beach 옆 야외 수영장. 캐나다에서 가장 긴 137m 풀로 유명. 5월부터 9월까지 시즌 오픈. 바다 전망과 함께 수영하는 경험으로 현지인과 관광객 모두에게 인기.',
  'Kitsilano Beach 옆 야외 수영장. 캐나다에서 가장 긴 137m 풀로 유명. 5월부터 9월까지 시즌 오픈. 바다 전망과 함께 수영하는 경험으로 현지인과 관광객 모두에게 인기.',
  '/mockup/images/lifestyle_002.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"lifestyle_002","name_en":"Kits Pool","name_kr":"키츠 풀","district":"Kitsilano","subcategory_display_kr":"스포츠 장소","original_source_type":"manual","data_quality":"mock","price_tier":"$","price_level":1,"korean_relevance_tags":["family_friendly","curated_for_vancouver_koreans"],"schedule":{"type":"recurring","openingHours":"Mon-Sun 7:00-20:45 (May-Sep only)","startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":3,"engagement":4,"production":4,"energy":4},"metadata":{"lifestyleSubtype":"sport_venue","isRecurring":true,"requiresMembership":false},"popularity_score":0.75,"freshness_score":0.65}$json$::jsonb,
  0.73,
  0.6,
  true,
  true,
  90,
  18,
  2,
  3.8,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '스탠리 파크 선라이즈 러너 (Stanley Park Sunrise Runners)',
  'event',
  'lifestyle',
  ARRAY['sport_meetup']::text[],
  'vancouver',
  'Vancouver',
  'Stanley Park Seawall (Lost Lagoon entrance), Vancouver, BC',
  49.3043,
  -123.1443,
  'low',
  ARRAY['active', 'outdoor', 'group_required', 'newcomer_friendly']::text[],
  ARRAY['sport_meetup', 'newcomer_friendly', 'curated_for_vancouver_koreans']::text[],
  '매주 화·목 아침 6시 30분 Stanley Park Seawall에서 만나 함께 달리는 러닝 크루. 5km·10km 두 그룹으로 나뉘어 진행. 운동 후 근처 카페에서 함께 커피. 초보 러너도 환영.',
  '매주 화·목 아침 6시 30분 Stanley Park Seawall에서 만나 함께 달리는 러닝 크루. 5km·10km 두 그룹으로 나뉘어 진행. 운동 후 근처 카페에서 함께 커피. 초보 러너도 환영.',
  '/mockup/images/lifestyle_003.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"lifestyle_003","name_en":"Stanley Park Sunrise Runners","name_kr":"스탠리 파크 선라이즈 러너","district":"Stanley Park","subcategory_display_kr":"스포츠 모임","original_source_type":"manual","data_quality":"mock","price_tier":"free","price_level":0,"korean_relevance_tags":["newcomer_friendly","curated_for_vancouver_koreans"],"schedule":{"type":"recurring","openingHours":"Tue, Thu 6:30-8:00","startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":3,"engagement":5,"production":2,"energy":5},"metadata":{"lifestyleSubtype":"sport_meetup","isRecurring":true,"requiresMembership":false},"popularity_score":0.75,"freshness_score":0.65}$json$::jsonb,
  0.73,
  0.67,
  true,
  true,
  90,
  18,
  2,
  3.8,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '캐넉스 vs 메이플 리프스 (Canucks vs Maple Leafs)',
  'event',
  'lifestyle',
  ARRAY['sports_schedule']::text[],
  'vancouver',
  'Vancouver',
  '800 Griffiths Way, Vancouver, BC V6B 6G1',
  49.2778,
  -123.1089,
  'high',
  ARRAY['lively', 'indoor', 'ticket_required', 'group_friendly']::text[],
  ARRAY['sports_schedule', 'curated_for_vancouver_koreans']::text[],
  'Rogers Arena에서 열리는 NHL 정규시즌 라이벌전. Vancouver Canucks와 Toronto Maple Leafs의 빅매치. 18,000석 매진 예상. 응원 분위기 절정의 캐나다 아이스하키 문화 경험 가능.',
  'Rogers Arena에서 열리는 NHL 정규시즌 라이벌전. Vancouver Canucks와 Toronto Maple Leafs의 빅매치. 18,000석 매진 예상. 응원 분위기 절정의 캐나다 아이스하키 문화 경험 가능.',
  '/mockup/images/lifestyle_004.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"lifestyle_004","name_en":"Canucks vs Maple Leafs","name_kr":"캐넉스 vs 메이플 리프스","district":"Downtown","subcategory_display_kr":"경기일정","original_source_type":"manual","data_quality":"mock","price_tier":"$$$","price_level":3,"korean_relevance_tags":["curated_for_vancouver_koreans"],"schedule":{"type":"one_time","openingHours":null,"startDateTime":"2026-06-12T19:00","endDateTime":"2026-06-12T22:00"},"dimension_scores":{"atmosphere":5,"engagement":2,"production":5,"energy":3},"metadata":{"lifestyleSubtype":"sports_schedule","isRecurring":false,"requiresMembership":false},"popularity_score":0.75,"freshness_score":0.59}$json$::jsonb,
  0.718,
  0.6,
  true,
  true,
  90,
  18,
  2,
  3.8,
  '2026-06-12T19:00:00-07:00',
  '2026-06-12T22:00:00-07:00',
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '밴쿠버 인터내셔널 재즈 페스티벌 (Vancouver International Jazz Festival)',
  'event',
  'lifestyle',
  ARRAY['festival']::text[],
  'vancouver',
  'Vancouver',
  '1300 Pacific Blvd, Vancouver, BC V6Z 2Y4',
  49.2727,
  -123.1207,
  'low',
  ARRAY['lively', 'outdoor', 'seasonal', 'free_entry']::text[],
  ARRAY['festival', 'curated_for_vancouver_koreans']::text[],
  '매년 6~7월 Vancouver 곳곳에서 열리는 도시 최대 음악 페스티벌. 무료 야외 공연부터 유료 클럽 공연까지 다양. 글로벌 재즈 아티스트 200+팀 참여. 10일간 진행되며 메인 무대는 David Lam Park.',
  '매년 6~7월 Vancouver 곳곳에서 열리는 도시 최대 음악 페스티벌. 무료 야외 공연부터 유료 클럽 공연까지 다양. 글로벌 재즈 아티스트 200+팀 참여. 10일간 진행되며 메인 무대는 David Lam Park.',
  '/mockup/images/lifestyle_005.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"lifestyle_005","name_en":"Vancouver International Jazz Festival","name_kr":"밴쿠버 인터내셔널 재즈 페스티벌","district":"Yaletown","subcategory_display_kr":"페스티벌","original_source_type":"manual","data_quality":"mock","price_tier":"$","price_level":1,"korean_relevance_tags":["curated_for_vancouver_koreans"],"schedule":{"type":"one_time","openingHours":null,"startDateTime":"2026-06-19T17:00","endDateTime":"2026-06-28T23:00"},"dimension_scores":{"atmosphere":4.5,"engagement":2.5,"production":5,"energy":3},"metadata":{"lifestyleSubtype":"festival","isRecurring":false,"requiresMembership":false},"popularity_score":0.75,"freshness_score":0.56}$json$::jsonb,
  0.712,
  0.6,
  true,
  true,
  90,
  18,
  2,
  3.8,
  '2026-06-19T17:00:00-07:00',
  '2026-06-28T23:00:00-07:00',
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '코퀴틀람 한국 문화 페스티벌 (Coquitlam Korean Cultural Festival)',
  'event',
  'lifestyle',
  ARRAY['festival']::text[],
  'coquitlam',
  'Coquitlam',
  '1299 Pinetree Way, Coquitlam, BC V3B 7Y3',
  49.2841,
  -122.7959,
  'low',
  ARRAY['family_event', 'outdoor', 'korean_community', 'free_entry']::text[],
  ARRAY['festival', 'korean_community', 'korean_friendly', 'family_friendly', 'curated_for_vancouver_koreans']::text[],
  '매년 6월 Town Centre Park에서 열리는 한인 커뮤니티 주최 문화 페스티벌. K-pop 댄스 공연, 전통 음식 부스, 한복 체험존, 한식 푸드트럭 다수. 가족 단위 한인과 현지인 모두 참여하는 캐주얼 분위기.',
  '매년 6월 Town Centre Park에서 열리는 한인 커뮤니티 주최 문화 페스티벌. K-pop 댄스 공연, 전통 음식 부스, 한복 체험존, 한식 푸드트럭 다수. 가족 단위 한인과 현지인 모두 참여하는 캐주얼 분위기.',
  '/mockup/images/lifestyle_006.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"lifestyle_006","name_en":"Coquitlam Korean Cultural Festival","name_kr":"코퀴틀람 한국 문화 페스티벌","district":"Coquitlam","subcategory_display_kr":"페스티벌","original_source_type":"manual","data_quality":"mock","price_tier":"free","price_level":0,"korean_relevance_tags":["korean_community","korean_friendly","family_friendly","curated_for_vancouver_koreans"],"schedule":{"type":"one_time","openingHours":null,"startDateTime":"2026-06-14T11:00","endDateTime":"2026-06-14T20:00"},"dimension_scores":{"atmosphere":4,"engagement":3,"production":3.5,"energy":3},"metadata":{"lifestyleSubtype":"festival","isRecurring":false,"requiresMembership":false},"popularity_score":0.68,"freshness_score":0.58}$json$::jsonb,
  0.658,
  0.9,
  true,
  true,
  82,
  16,
  2,
  3.4,
  '2026-06-14T11:00:00-07:00',
  '2026-06-14T20:00:00-07:00',
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '매기 로저스 라이브 앳 오르피움 (Maggie Rogers Live at Orpheum)',
  'event',
  'lifestyle',
  ARRAY['concert']::text[],
  'vancouver',
  'Vancouver',
  '601 Smithe St, Vancouver, BC V6B 5G1',
  49.281,
  -123.1218,
  'high',
  ARRAY['lively', 'indoor', 'ticket_required', 'vintage']::text[],
  ARRAY['concert', 'curated_for_vancouver_koreans']::text[],
  'Orpheum Theatre에서 열리는 Maggie Rogers의 캐나다 투어 단독 공연. 1920년대 빈티지 극장의 고풍스러운 인테리어와 어쿠스틱 사운드 시스템. 인디 팝·포크 팬 사이에서 화제. 전석 지정.',
  'Orpheum Theatre에서 열리는 Maggie Rogers의 캐나다 투어 단독 공연. 1920년대 빈티지 극장의 고풍스러운 인테리어와 어쿠스틱 사운드 시스템. 인디 팝·포크 팬 사이에서 화제. 전석 지정.',
  '/mockup/images/lifestyle_007.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"lifestyle_007","name_en":"Maggie Rogers Live at Orpheum","name_kr":"매기 로저스 라이브 앳 오르피움","district":"Downtown","subcategory_display_kr":"콘서트","original_source_type":"manual","data_quality":"mock","price_tier":"$$$","price_level":3,"korean_relevance_tags":["curated_for_vancouver_koreans"],"schedule":{"type":"one_time","openingHours":null,"startDateTime":"2026-05-25T20:00","endDateTime":"2026-05-25T23:00"},"dimension_scores":{"atmosphere":4,"engagement":2,"production":4.5,"energy":3},"metadata":{"lifestyleSubtype":"concert","isRecurring":false,"requiresMembership":false},"popularity_score":0.68,"freshness_score":0.8}$json$::jsonb,
  0.702,
  0.6,
  true,
  true,
  82,
  16,
  2,
  3.4,
  '2026-05-25T20:00:00-07:00',
  '2026-05-25T23:00:00-07:00',
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '라이트하우스 파크 (Lighthouse Park)',
  'place',
  'lifestyle',
  ARRAY['nature']::text[],
  'west_vancouver',
  'West Vancouver',
  'Beacon Ln, West Vancouver, BC V7W 1K6',
  49.3326,
  -123.2616,
  'low',
  ARRAY['outdoor', 'nature_immersive', 'free_entry', 'solo_friendly']::text[],
  ARRAY['nature', 'curated_for_vancouver_koreans']::text[],
  'West Vancouver 끝자락의 75만 평방미터 자연 보호 공원. 오래된 수목과 태평양을 한눈에 보는 트레일이 여러 갈래. Point Atkinson 등대가 시그니처 포인트. 차분한 산책에 적합.',
  'West Vancouver 끝자락의 75만 평방미터 자연 보호 공원. 오래된 수목과 태평양을 한눈에 보는 트레일이 여러 갈래. Point Atkinson 등대가 시그니처 포인트. 차분한 산책에 적합.',
  '/mockup/images/lifestyle_008.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"lifestyle_008","name_en":"Lighthouse Park","name_kr":"라이트하우스 파크","district":"West Vancouver","subcategory_display_kr":"자연","original_source_type":"manual","data_quality":"mock","price_tier":"free","price_level":0,"korean_relevance_tags":["curated_for_vancouver_koreans"],"schedule":{"type":"always_open","openingHours":null,"startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":1.5,"engagement":3,"production":2,"energy":3.5},"metadata":{"lifestyleSubtype":"nature","isRecurring":false,"requiresMembership":false},"popularity_score":0.5,"freshness_score":0.65}$json$::jsonb,
  0.53,
  0.6,
  true,
  true,
  60,
  12,
  1,
  2.5,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  '쿼리 락 트레일 (Quarry Rock Trail)',
  'place',
  'lifestyle',
  ARRAY['nature']::text[],
  'north_vancouver',
  'North Vancouver',
  'Panorama Dr, North Vancouver, BC',
  49.3286,
  -122.9509,
  'low',
  ARRAY['outdoor', 'nature_immersive', 'active', 'free_entry']::text[],
  ARRAY['nature', 'curated_for_vancouver_koreans']::text[],
  'Deep Cove에서 시작하는 왕복 4km 등산 트레일. 정상에서는 Indian Arm 협만의 절경. 중급 난이도로 1.5~2시간 소요. 등산 후 Deep Cove 마을의 도넛 가게 Honey Doughnuts가 단골 코스.',
  'Deep Cove에서 시작하는 왕복 4km 등산 트레일. 정상에서는 Indian Arm 협만의 절경. 중급 난이도로 1.5~2시간 소요. 등산 후 Deep Cove 마을의 도넛 가게 Honey Doughnuts가 단골 코스.',
  '/mockup/images/lifestyle_009.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"lifestyle_009","name_en":"Quarry Rock Trail","name_kr":"쿼리 락 트레일","district":"North Vancouver","subcategory_display_kr":"자연","original_source_type":"manual","data_quality":"mock","price_tier":"free","price_level":0,"korean_relevance_tags":["curated_for_vancouver_koreans"],"schedule":{"type":"always_open","openingHours":null,"startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":2,"engagement":4.5,"production":1.5,"energy":4.5},"metadata":{"lifestyleSubtype":"nature","isRecurring":false,"requiresMembership":false},"popularity_score":0.62,"freshness_score":0.65}$json$::jsonb,
  0.629,
  0.6,
  true,
  true,
  74,
  15,
  1,
  3.1,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
),
(
  'UBC 인류학 박물관 (Museum of Anthropology at UBC)',
  'place',
  'lifestyle',
  ARRAY['culture']::text[],
  'vancouver',
  'Vancouver',
  '6393 NW Marine Dr, Vancouver, BC V6T 1Z2',
  49.2696,
  -123.2589,
  'low',
  ARRAY['indoor', 'learning_heavy', 'solo_friendly', 'instagrammable']::text[],
  ARRAY['culture', 'student_friendly', 'curated_for_vancouver_koreans']::text[],
  'UBC 캠퍼스 내 위치한 국제적 명성의 인류학 박물관. First Nations 문화 컬렉션과 글로벌 토착민 예술 전시. 건축물 자체도 명작으로 꼽히며 영화 촬영지로도 자주 사용됨.',
  'UBC 캠퍼스 내 위치한 국제적 명성의 인류학 박물관. First Nations 문화 컬렉션과 글로벌 토착민 예술 전시. 건축물 자체도 명작으로 꼽히며 영화 촬영지로도 자주 사용됨.',
  '/mockup/images/lifestyle_010.jpg',
  'curated',
  $json${"seed_batch":"dooridoori_mvp_mock_v1","mock_id":"lifestyle_010","name_en":"Museum of Anthropology at UBC","name_kr":"UBC 인류학 박물관","district":"UBC","subcategory_display_kr":"문화","original_source_type":"manual","data_quality":"mock","price_tier":"$","price_level":1,"korean_relevance_tags":["student_friendly","curated_for_vancouver_koreans"],"schedule":{"type":"recurring","openingHours":"Tue-Sun 10:00-17:00, Closed Mon","startDateTime":null,"endDateTime":null},"dimension_scores":{"atmosphere":1.5,"engagement":2,"production":4.5,"energy":2},"metadata":{"lifestyleSubtype":"culture","isRecurring":false,"requiresMembership":false},"popularity_score":0.5,"freshness_score":0.65}$json$::jsonb,
  0.53,
  0.65,
  true,
  true,
  60,
  12,
  1,
  2.5,
  null,
  null,
  '2026-05-10T00:00:00Z',
  '2026-05-10T00:00:00Z'
);

commit;

-- Quick checks:
-- select category, count(*) from public.content_items where source_refs->>'seed_batch' = 'dooridoori_mvp_mock_v1' group by category order by category;
-- select title, category, area, budget_level, quality_score, korean_community_fit from public.content_items where source_refs->>'seed_batch' = 'dooridoori_mvp_mock_v1' order by category, title;